language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:  
  - SIC_AFIP_ENV="testing" BUCKET_NAME="" AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY="" AWS_DEFAULT_REGION="" SIC_MAIL_ENV="testing" RECAPTCHA_SECRET_KEY="" RECAPTCHA_TEST_KEY="111111"
addons:
  sonarcloud:
    organization: "globo-technology"
script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
